version: "3.3"
services:
  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: "mauricio"
    ports:
      - "3309:3309"
  
  web:
    build: .
    working_dir: /ac-fullstack #AQUI É DECLARADO O DIRETORIO QUE IRAR SE COLOCADO DENTRO DO CONTEINER ?
    command: python app.py #AQUI SERÁ EXECULTADO O PYTHON PASSANDO O ARQUIVO APP.PY
    links:
      - db                  #DECLARAÇÃO DO LINK DO BANCO MYSQL?
    volumes:
      - .:/data 
      - ./templates:/ac-fullstack/templates
    ports:
      - "5002:5002"
